apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      # - name: external
      #   port: 9094
      #   type: nodeport
      #   tls: false
      #   configuration:
      #     brokers:
      #     - broker: 0
      #       advertisedHost: localhost
      #     - broker: 1
      #       advertisedHost: localhost
      #     - broker: 2
      #       advertisedHost: localhost
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2

      # num.network.threads: 3
      # num.io.threads: 8
      # num.recovery.threads.per.data.dir: 1
      # socket.send.buffer.bytes: 102400
      # socket.receive.buffer.bytes: 102400
      # socket.request.max.bytes: 104857600


      # num.network.threads: 4
      # num.io.threads: 8
      # num.replica.fetchers: 2

    jvmOptions:
      # -Xms: 2g
      # -Xmx: 2g
      # "-XX":
      #   "UseG1GC": "true"
      #   "MaxGCPauseMillis": "20"
      #   "InitiatingHeapOccupancyPercent": "35"
      #   "ExplicitGCInvokesConcurrent": "true"
    # resources:
    #   requests:
    #     memory: "2Gi"
    #     cpu: "2"     # Requests 2 cores (Kubernetes allows bursting to limit)
    #   limits:
    #     memory: "2Gi"
    #     cpu: "4"     # Limit to 4 cores


  entityOperator:
    topicOperator: {}
    userOperator: {}