apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: f7-app:latest
        args: ["store"]
        env:
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap:9092"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: store
spec:
  selector:
    app: store
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
