apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: app
      containers:
      - name: api
        image: registry.digitalocean.com/f7-repo/flash7
        args: ["api"]

        env:
        - name: PORT
          value: "3000"
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
        - name: STORE_SHARDS
          value: "http://store.app.svc:4000"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: f7-repo
      # affinity:
      #         podAntiAffinity:
      #           requiredDuringSchedulingIgnoredDuringExecution:
      #             - labelSelector:
      #                 matchLabels:
      #                   app: kafka  # This matches the label of the Kafka pods or namespace
      #               topologyKey: kubernetes.io/hostname  # Prevent placement on the same node
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
